src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Title cannot be empty.")
     * @Assert\Length(
     * min = 3,
     * max = 255,
     * minMessage = "Book title must be at least {{ limit }} characters long.",
     * maxMessage = "Book title cannot be longer than {{ limit }} characters."
     * )
     * @Assert\Regex(
     * pattern="/[@#$%^<>|~]/",
     * match=false,
     * message="Book title cannot contain symbols @#$%^<>|~."
     * )
     */
    private $title;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Pages cannot be empty.")
     * @Assert\Positive(message="Pages must be positive number.")
     */
    private $pages;

    /**
     * @ORM\Column(type="string", length=64)
     * @Assert\NotBlank(message="Isbn cannot be empty.")
     * @Assert\Length(
     * min = 3,
     * max = 64,
     * minMessage = "Isbn must be at least {{ limit }} characters long.",
     * maxMessage = "Isbn cannot be longer than {{ limit }} characters."
     * )
     * @Assert\Regex(
     * pattern="/^[a-z\d\-\s]+$/",
     * match=true,
     * message="Isbn can contain letters, digits, spaces and - only."
     * )
     */
    private $isbn;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="Short description cannot be empty.")
     * @Assert\Regex(
     * pattern="/^[#^<>|~]+$/",
     * match=false,
     * message="Short description cannot contain symbols #^<>|~."
     * )
     */
    private $short_description;

    /**
     * @ORM\Column(type="integer")
     */
    private $author_id;

    /**
     * @ORM\ManyToOne(targetEntity=Author::class, inversedBy="books")
     */
    private $author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): self
    {
        $this->pages = $pages;

        return $this;
    }

    public function getIsbn(): ?string
    {
        return $this->isbn;
    }

    public function setIsbn(string $isbn): self
    {
        $this->isbn = $isbn;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->short_description;
    }

    public function setShortDescription(string $short_description): self
    {
        $this->short_description = $short_description;

        return $this;
    }

    public function getAuthorId(): ?int
    {
        return $this->author_id;
    }

    public function setAuthorId(int $author_id): self
    {
        $this->author_id = $author_id;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->author;
    }

    public function setAuthor(?Author $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use App\Entity\Author;
use App\Entity\Book;

class BookController extends AbstractController
{
    /**
     * @Route("/book", name="book_index")
     */
    public function index(Request $r): Response
    {

        $books = $this->getDoctrine()
        ->getRepository(Book::class);

        $authors = $this->getDoctrine()
        ->getRepository(Author::class)
        ->findAll();

        if ($r->query->get('author_id') !== null){
            if ($r->query->get('author_id') == 'view_all'){
                $books = $books->findBy([],['title'=>'asc']);;
            } else {
                $books = $books->findBy(['author_id' => $r->query->get('author_id')], ['title' => 'asc']);
            }
        } else {
            $books = $books->findBy([],['title'=>'asc']);;
        }

        return $this->render('book/index.html.twig', [
            'books' => $books,
            'authors' => $authors,
            'author_id' => $r->query->get('author_id') ?? '0',
            'success' => $r->getSession()->getFlashBag()->get('success', [])
        ]);
    }

    /**
    * @Route("/book/create", name="book_create", methods={"GET"})
    */
    public function create(Request $r): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $book_title = $r->getSession()->getFlashBag()->get('book_title', []);
        $book_isbn = $r->getSession()->getFlashBag()->get('book_isbn', []);
        $book_pages = $r->getSession()->getFlashBag()->get('book_pages', []);
        $book_about = $r->getSession()->getFlashBag()->get('book_about', []);
        $book_author_id = $r->getSession()->getFlashBag()->get('book_author_id', []);

        $authors = $this->getDoctrine()
        ->getRepository(Author::class)
        ->findBy([],['surname'=>'asc']);

        return $this->render('book/create.html.twig', [
            'authors' => $authors,
            'errors' => $r->getSession()->getFlashBag()->get('errors', []),
            'book_title' => $book_title[0] ?? '',
            'book_isbn' => $book_isbn[0] ?? '',
            'book_pages' => $book_pages[0] ?? '',
            'book_about' => $book_about[0] ?? '',
            'book_author_id' => $book_author_id[0] ?? ''
        ]);
    }

    /**
    * @Route("/book/store", name="book_store", methods={"POST"})
    */
    public function store(Request $r, ValidatorInterface $validator): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $submittedToken = $r->request->get('token');

        if (!$this->isCsrfTokenValid('token', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Bad token - CSRF');
            return $this->redirectToRoute('book_create');
        }

        $author = $this->getDoctrine()
        ->getRepository(Author::class)
        ->find($r->request->get('book_author_id'));

        if($author == null){
            $r->getSession()->getFlashBag()->add('errors', "Author must be selected.");
        }

        $book = new Book;

        $book->
        setTitle($r->request->get('book_title'))->
        setIsbn($r->request->get('book_isbn'))->
        setPages((int)$r->request->get('book_pages'))->
        setShortDescription($r->request->get('book_about'))->
        setAuthor($author);

        $errors = $validator->validate($book);

        if (count($errors) > 0) {
            foreach ($errors as $key => $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }

            $r->getSession()->getFlashBag()->add('book_title', $r->request->get('book_title'));
            $r->getSession()->getFlashBag()->add('book_isbn', $r->request->get('book_isbn'));
            $r->getSession()->getFlashBag()->add('book_pages', $r->request->get('book_pages'));
            $r->getSession()->getFlashBag()->add('book_about', $r->request->get('book_about'));
            $r->getSession()->getFlashBag()->add('book_author_id', $r->request->get('book_author_id'));

            return $this->redirectToRoute('book_create');
        }

        if($author == null){
            $r->getSession()->getFlashBag()->add('book_title', $r->request->get('book_title'));
            $r->getSession()->getFlashBag()->add('book_isbn', $r->request->get('book_isbn'));
            $r->getSession()->getFlashBag()->add('book_pages', $r->request->get('book_pages'));
            $r->getSession()->getFlashBag()->add('book_about', $r->request->get('book_about'));
            return $this->redirectToRoute('book_create');
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($book);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Book has been added succesfully.');

        return $this->redirectToRoute('book_index');
    }

    /**
    * @Route("/book/edit/{id}", name="book_edit", methods={"GET"})
    */
    public function edit(Request $r, int $id): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $book = $this->getDoctrine()
        ->getRepository(Book::class)
        ->find($id);

        $book_title = $r->getSession()->getFlashBag()->get('book_title', []);
        $book_isbn = $r->getSession()->getFlashBag()->get('book_isbn', []);
        $book_pages = $r->getSession()->getFlashBag()->get('book_pages', []);
        $book_about = $r->getSession()->getFlashBag()->get('book_about', []);
        $book_author_id = $r->getSession()->getFlashBag()->get('book_author_id', []);

        $authors = $this->getDoctrine()
        ->getRepository(Author::class)
        ->findBy([],['surname'=>'asc']);

        return $this->render('book/edit.html.twig', [
            'book' => $book,
            'authors' => $authors,
            'errors' => $r->getSession()->getFlashBag()->get('errors', []),
            'book_title' => $book_title[0] ?? '',
            'book_isbn' => $book_isbn[0] ?? '',
            'book_pages' => $book_pages[0] ?? '',
            'book_about' => $book_about[0] ?? '',
            'book_author_id' => $book_author_id[0] ?? ''
        ]);
    }

    /**
    * @Route("/book/update/{id}", name="book_update", methods={"POST"})
    */
    public function update(Request $r, $id, ValidatorInterface $validator): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        $submittedToken = $r->request->get('token');

        if (!$this->isCsrfTokenValid('token', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Bad token - CSRF');
            return $this->redirectToRoute('book_edit', ['id'=>$book->getId()]);
        }

        $book = $this->getDoctrine()
        ->getRepository(Book::class)
        ->find($id);

        $book->
        setTitle($r->request->get('book_title'))->
        setIsbn($r->request->get('book_isbn'))->
        setPages((int)$r->request->get('book_pages'))->
        setShortDescription($r->request->get('book_about'))->
        setAuthorId($r->request->get('book_author_id'));

        $errors = $validator->validate($book);

        if (count($errors) > 0) {
            foreach ($errors as $key => $error) {
                $r->getSession()->getFlashBag()->add('errors', $error->getMessage());
            }

            $r->getSession()->getFlashBag()->add('book_title', $r->request->get('book_title'));
            $r->getSession()->getFlashBag()->add('book_isbn', $r->request->get('book_isbn'));
            $r->getSession()->getFlashBag()->add('book_pages', $r->request->get('book_pages'));
            $r->getSession()->getFlashBag()->add('book_about', $r->request->get('book_about'));
            $r->getSession()->getFlashBag()->add('book_author_id', $r->request->get("book_author_id"));

            return $this->redirectToRoute('book_edit', ['id'=>$book->getId()]);
        }

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($book);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Book changes has been saved.');


        return $this->redirectToRoute('book_index');
    }

    /**
    * @Route("/book/delete/{id}", name="book_delete", methods={"POST"})
    */
    public function delete(Request $r, $id): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        
        $submittedToken = $r->request->get('token');

        if (!$this->isCsrfTokenValid('token', $submittedToken)) {
            $r->getSession()->getFlashBag()->add('errors', 'Bad token - CSRF');
            return $this->redirectToRoute('book_index');
        }     
        
        $book = $this->getDoctrine()
        ->getRepository(Book::class)
        ->find($id);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->remove($book);
        $entityManager->flush();

        $r->getSession()->getFlashBag()->add('success', 'Book has been successfully deleted.');


        return $this->redirectToRoute('book_index');
    }


}

templates/book/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add New Book
{% endblock %}

{% block body %}

	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						<h1>Add new Book</h1>
					</div>

					<div class="card-body">
						<form action="{{path('book_store')}}" method="POST">

							<div class="form-group">
								<label>Author:</label>
								<select name="book_author_id" class="form-control">
									<option value="0">Select author</option>
									{% for author in authors %}
										<option value="{{author.id}}" {% if author.id == book_author_id %} selected {% endif %}>
											{{author.name}}
											{{author.surname}}
										</option>
									{% endfor %}
								</select>
							</div>

							<div class="form-group">
								<label>Title:</label>
								<input class="form-control" type="text" name="book_title" value="{{book_title}}">
							</div>

							<div class="form-group">
								<label>Pages:</label>
								<input class="form-control" type="text" name="book_pages" value="{{book_pages}}">
							</div>

							<div class="form-group">
								<label>ISBN:</label>
								<input class="form-control" type="text" name="book_isbn" value="{{book_isbn}}">
							</div>

							<div class="form-group">
								Short description:<textarea name="book_about" id="summernote">{{book_about}}</textarea>
							</div>

							<div class="row justify-content-center">
								<button class="btn btn-light button-big text-center" type="submit">Add new Book</button>
							</div>
							<input type="hidden" name="token" value="{{ csrf_token('token') }}"/>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/book/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Book
{% endblock %}

{% block body %}

	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">
				<div class="card">
					<div class="card-header">
						<h1>Edit book</h1>
					</div>
					<div class="card-body">
						<form action="{{path('book_update', {id: book.id})}}" method="POST">


							<div class="form-group">
								<label>Author:</label>
								<select class="form-control" name="book_author_id">
									<option value="0">Select Author</option>
									{% for author in authors %}
										<option value="{{author.id}}" {% if author.id == book.AuthorId %} selected {% endif %}>
											{{author.name}}
											{{author.surname}}
										</option>
									{% endfor %}
								</select>
							</div>

							<div class="form-group">
								<label>Title:</label>
								<input class="form-control" type="text" name="book_title" value="{{book.title}}">
							</div>

							<div class="form-group">
								<label>Pages:</label>
								<input class="form-control" type="text" name="book_pages" value="{{book.pages}}">
							</div>

							<div class="form-group">
								<label>ISBN:</label>
								<input class="form-control" type="text" name="book_isbn" value="{{book.isbn}}">
							</div>


							<div class="form-group">
								Short description:<textarea id="summernote" name="book_about">{{book.shortDescription}}</textarea>
							</div>


							<div class="row justify-content-center">
								<button class="btn btn-light button-big" type="submit">Save</button>
							</div>
							<input type="hidden" name="token" value="{{ csrf_token('token') }}"/>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}List of the Books
{% endblock %}

{% block body %}

	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-8">

				<div class="card">

					<div class="card-header">
						<h1>Books in the Library</h1>
					</div>

					<div class="card-body">

						{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
							<div class="row justify-content-center">
								<div class="form-group">
									<a class="btn btn-light button" href="{{path('book_create')}}">Add new book</a>
								</div>
							</div>
						{% endif %}

						{# TIKRINU AR YRA SARASE KNYGU #}
						{% if books|length <= 0 %}
							<div class="row justify-content-center">
								<div class="form-group">
									<h6>There are no Books in the library.</h6>
								</div>
							</div>
						{% else %}

							{# SORTINIMAS #}
							<div class="form-group filter-title">
								Filter by:
							</div>
							<div class="order form-group">
								<span class="order-text">Author:</span>
								<div class="order-select">
									<form action="{{path('book_index')}}" method="GET" class="order-form">
										<select name="author_id" class="order-select">
											<option value="view_all">view all</option>
											{% for author in authors %}
												{% if author.books|length > 0 %}
													<option value="{{author.id}}" {% if author_id == author.id %} selected {% endif %}>{{author.name}}
														{{author.surname}}</option>
												{% endif %}
											{% endfor %}
										</select>
										<button class="btn btn-light button button-filter button-block" type="submit">Filter</button>
										<a class="btn btn-light button button-filter" href="{{path('book_index')}}">Clear</a>
									</form>
								</div>
							</div>

							{# KNYGU SARASAS #}
							<ul class="list-group">
								{% for book in books %}
									{# viena knyga #}
									<li class="list-group-item">
										<div class="list-group-item__line">
											<span class="author-name">
												<h5>{{book.title}}</h5>
											</span>
											{% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
												<div class="list-group-item__line__buttons">
													<a class="btn btn-light button button-edit" href="{{ path('book_edit', {id:book.id}) }}">Edit</a>
												</div>
												<form class="delete-button" action="{{path('book_delete', {id: book.id})}}" method="POST">
													<button class="btn btn-light button button-delete" type="submit">
														Delete
													</button>
													<input type="hidden" name="token" value="{{ csrf_token('token') }}"/>
												</form>
											{% endif %}
										</div>
										<h5>
											<span class="badge badge-secondary">More info:</span>
										</h5>
										<ul class="list-group">
											<li class="list-group-item book-item">Author:
												{{book.author.name}}
												{{book.author.surname}}</li>
											<li class="list-group-item book-item">Pages:
												{{book.pages}}</li>
										</ul>
									</li>
								{% endfor %}
							</ul>
						{% endif %}


					{% endblock %}